name: CI

on: [push]

jobs:
  seafile_job:
    runs-on: ubuntu-18.04
    name: A job to build and push the docker images for Seafile on ARMv7
    steps:
    - name: Build seafile-docker on armv7
      uses: uraimo/run-on-arch-action@master
      with:
        architecture: armv7
        distribution: ubuntu18.04
        run: |
          set -e
          ls -l
          export DEBIAN_FRONTEND=noninteractive
          echo "Apt::Install-Recommends 'false';" >/etc/apt/apt.conf.d/02no-recommends
          echo "Acquire::Languages { 'none' };" >/etc/apt/apt.conf.d/05no-languages
          apt-get update
          apt-get install git wget
          wget -qO- https://get.docker.com/ | sh
          git clone https://github.com/zudljk/seafile-docker
          cd seafile-docker/image
          docker login -u zudljk -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          export server_image=zudljk/seafile-mc:7.1
          export latest_server_image=zudljk/seafile-mc:latest
          cd seafile_7.1 && cp -rf ../../scripts_7.1 ./ && docker build -t ${server_image} .
          docker tag ${server_image}-squashed ${server_image}
          docker tag ${server_image} ${latest_server_image}
          docker rmi `docker images --filter "dangling=true" -q --no-trunc`
          docker push ${server_image}
          docker push ${latest_server_image}
