name: CI

on: [push]

jobs:
  testactions_job:
    runs-on: ubuntu-18.04
    name: A job to test the multi architecture actions
    steps:
    - name: Build with Swift on armv7
      uses: uraimo/run-on-arch-action@master
      with:
        architecture: armv7
        distribution: ubuntu18.04
        run: |
          apt update
          apt install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
          add-apt-repository "deb [arch=armhf] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          apt update
          apt install -y docker-ce
          ls
