name: CI

on: [push]

jobs:
  seafile_job:
    runs-on: ubuntu-18.04
    name: A job to build and push the docker images for Seafile on ARMv7
    steps:
    - name: Build seafile-docker on armv7
      uses: uraimo/run-on-arch-action@master
      with:
        architecture: armv7
        distribution: ubuntu18.04
        run: |
          set +x
          apt update
          apt install -y apt-transport-https ca-certificates curl software-properties-common build-essential python-pip
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
          add-apt-repository "deb [arch=armhf] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          apt update
          apt install -y docker-ce
          pip install docker-squash
          git clone https://github.com/zudljk/seafile-docker
          cd seafile-docker/image
          make base push-base server push-server
